export const ENV_KEYS = [
  'TORRENT_PROVIDER_BASE_URL',
  'TORRENT_PROVIDER_USERNAME',
  'TORRENT_PROVIDER_PASSWORD',
  'TORRENT_DOWNLOAD_PATH',
  'ARGON2_MEMORY_COST',
  'ARGON2_TIME_COST',
  'ARGON2_SECRET',
];
